### ISSUE TITLE
Tag set join, feature request or doable?

### ISSUE THREAD

**Issue by arriflex** [CitiLogics/citilogics-geoloop-panel#12]
I would like to join geoJSON to an Influx metric where the Series GeoID Tag would actually be a pair of group by tags, aka tag set. 

Since there is only one field in GeoLoop for Series GeoID Tag I'm guessing I'd have to use an Alias By in order to create a compound reference. 

Thoughts?

**Comment by samhatchett** [comment]
interesting! so, to clarify, if your influx data were schematized as such:
`temperature,units=c,asset_type=building,asset=front_office`
... and your geojson has a polygon labelled as such:
`{"type":"Feature","properties":{"location":"building_front_office"},"geometry":{"type":"Polygon","coordinates": ...`

... then it should in theory be possible to use the alias `$m {location:$tag_asset_type_$tag_asset}` to generate the correct lookup value joining `asset_type=building,asset=front_office` to `{"location":"building_front_office"}`. the problem is I don't think Grafana will let us assemble the string this way. The real solution would be to either re-do the influx tags, or add some kind of more sophisticated matching engine in this plugin. 

GeoLoop right now uses regex capture group to find the metric tag it needs to map into the GeoJSON:
https://github.com/CitiLogics/citilogics-geoloop-panel/blob/55585bf1a6b4549308b12f9bb8bddfc6ddfa0332/src/geoloop_ctrl.js#L317

... so we could possibly expose a pair of regex replacement strings to the user, to allow an arbitrary transformation from the tag-space into the geo-space. For the example above, something like 
```
input: /asset=([^,}]+),asset_type=([^,}]+)/
output: "$1_$2"
```

**Comment by arriflex** [comment]
I've got it working with the Alias By for now. Eventually I'll provide the metric a cleaner, single tag which will represent the compound tags so that it doesn't have to do it during runtime when I redo the schema (considering moving to TimescaleDB). 

But yes, you got the idea. And seriously, this is the coolest Grafana plugin ever!
